### ISSUE TITLE
#1 There should be some kind of description on the sign up page that tells a user what the app does.

### ISSUE THREAD

**Issue by JamesHoran** [ninogogol/entertainment-web-app-master#1]
If you're open to it, I would love to contribute, but if this is something you want to do solo, I understand.

**Comment by ninogogol** [comment]
Hi James,

Thank you for your interest in contributing to the entertainment-web-app-master project! I'm definitely open to collaboration, and I think it could be a great learning experience for both of us. I'm new to collaborating with others on projects like this, but I'm excited to give it a try.

Regarding the issue you raised, I agree that adding a description to the sign-up page would be helpful for users. Since you already have access to the code in my public repository, feel free to create a fork of the repository, review the implementation for the login and sign-up pages, and share any suggestions you have for the description or other improvements by creating a pull request.

Before you start working on the project, please note that we use a `.env` file to store sensitive information like the Secret Key. You'll need to create your own `.env` file in your local copy of the project and add your own Secret Key for testing purposes. If you need any help with setting up the `.env` file or have any questions about the project setup, feel free to reach out.

Once we decide on the details, we can either divide the work or work on it together, depending on your preference. Feel free to share any other ideas or suggestions you have for the project as well. I'm looking forward to working with you!

Best regards,
Nino

**Comment by JamesHoran** [comment]
Sounds fantastic! I will let you know if I have any questions. For now I will be figuring out how to set up a .env file.

**Comment by JamesHoran** [comment]
I don't know if writing comments is the best way to communicate between us, so if you have any specific app you like to use to communicate, let me know. 

I think I set up my .env file correctly. I assigned SECRET_KEY to equal a string, but I am still having trouble signing up using the app. I don't know if this is because the app just isn't to that stage yet or because I set up something incorrectly.

**Comment by ninogogol** [comment]
You can find me on Discord with the username ```Nino Gogoladze#4817```. Regarding the .env file, follow these steps:

1. Create a new file in the root directory of your project.
2. Name the file ".env".
3. Open the .env file with a text editor.
4. Add the following line to the file: 
````SECRET_KEY=your_secret_key_value````

Replace ```your_secret_key_value``` with the actual secret key you want to use. Don't forget that when you start the server in your terminal, you should call 'npm install' to ensure that all dependencies are properly installed.
After setting up the .env file and ensuring all dependencies are installed with ```npm install```, make sure to start the server, and ensure it is running properly.
